### PR TITLE
Update to Ember 3.28

### PR DESCRIPTION
**Pull request by locks**
Updated using ember-cli-update and then ran the codemods. Not a lot of changes with the codemods though :P

### CODE REVIEW

**Comment by locks** [comment]
@jenweber I _think_ the Percy changes are from switching to the angle bracket syntax, it introduces more whitespace? Let me know if it's worth it to dig more into it.

**Review by ijlee2 — APPROVED** [review]
The upgrade looks good to me. I checked the Percy diff and the Netlify preview, and think it's okay to merge the pull request.

Unless the difference in line height (I think) causes an issue with printing the book, I don't think we need to spend much time investigating the cause.

**Comment by ijlee2** [comment]
@locks I merged #29, which had modified `yarn.lock`. Could you rebase your branch?

**Review by ijlee2 — APPROVED** [review]
Thanks for working on upgrading the app!

**Pull request merged**
